### ISSUE TITLE
Please update this library on actual Apollo Client version 

### ISSUE THREAD

**Issue by StIch0** [carvajalconsultants/apollo-link-offline#12]

**Comment by dtygel** [comment]
There is a nice fork which updates to apollo 3. Is there any interest in merging? Here it is: https://github.com/DanijelBojcic/apollo-link-offline

**Comment by miguelocarvajal** [comment]
@dtygel Certainly! Can you get a PR in place, I'll handle the rest. :)

**Comment by inkiltie** [comment]
Great library. Does the exact thing I wanted: make mutations survive page reload when offline and fire them again when back online.

Initially the package was failing on me with this error:
```
export { default, syncStatusQuery } from "./OfflineLink";
^^^^^^
SyntaxError: Unexpected token 'export'
```

Turned out this issue only exist in Next.js (when rendering `import OfflineLink from "apollo-link-offline";`). This happens because of Next.js standardization and module transpilation. There are many solutions how to avoid this error [described here](https://stackoverflow.com/questions/65936222/next-js-syntaxerror-unexpected-token-export ) if anyone will face such same issue as me. 

Also, I can confirm the package works without any issue in web app with async storage proposed here: https://github.com/carvajalconsultants/apollo-link-offline/issues/2#issuecomment-482827673

Thanks.

**Comment by miguelocarvajal** [comment]
@inkiltie Awesome! Glad to hear it worked well for you. :)
