### ISSUE TITLE
Remove spread operator for IE/Edge Support

### ISSUE THREAD

**Issue by FloNeu** [carvajalconsultants/apollo-link-offline#5]
I was trying to use this package in my quest to get my offline support working with apollo client - but noticed that i get SCRIPT1028: Expected identifier, string or number in Edge. It seems to come from your use of the spread operator that is not yet supported in Edge and will not be supported in Internet-Explorer.

Thx for your work.

**Comment by miguelocarvajal** [comment]
Hey @FloNeu 

Thanks for reaching out!

This issue has actually been reported, it's due to your setup not transpiling the code, see this issue:
https://github.com/carvajalconsultants/apollo-link-offline/issues/3#issuecomment-486726835

If you transpile your code with Babel for example, you'll be able to use it in Edge just fine.
